// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Robot = (function(_super) {

    __extends(Robot, _super);

    function Robot() {
      return Robot.__super__.constructor.apply(this, arguments);
    }

    Robot.prototype.defaults = {
      dir: 0,
      hp: 100,
      maxHP: 100,
      damage: 5,
      name: "robot",
      position: {
        x: 0,
        y: 0
      },
      speed: {
        x: 0,
        y: 0
      }
    };

    Robot.prototype.die = function() {
      return console.log("" + this.attributes.name + " has died");
    };

    return Robot;

  })(Backbone.Model);

}).call(this);
